import { MD3LightTheme } from "react-native-paper";

export const theme = {
  ...MD3LightTheme,

  colors: {
    ...MD3LightTheme.colors,
    primary: "#ea580c",
    primaryContainer: "#ffedd5",
    onPrimary: "#ffffff",
    onPrimaryContainer: "#7c2d12",
    secondary: "#14946d",
    secondaryContainer: "#d8faea",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#124d3c",
    tertiary: "#ca8a04",
    tertiaryContainer: "#fef9c3",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#713f12",
    error: "#e11d48",
    errorContainer: "#ffe4e6",
    success: "#1eb885",
    warning: "#eab308",
    info: "#0ea5e9",
    background: "#fff7ed",
    onBackground: "#0f172a",
    surface: "#fffbeb",
    onSurface: "#0f172a",
    surfaceVariant: "#fef3c7",
    onSurfaceVariant: "#475569",
    elevation: {
      level0: "transparent",
      level1: "#fffaf0",
      level2: "#fff5e6",
      level3: "#ffedd5",
      level4: "#fee2b9",
      level5: "#fed7aa",
    },
    outline: "#cbd5e1",
    outlineVariant: "#e2e8f0",
    backdrop: "rgba(20, 148, 109, 0.12)",
    shadow: "#000000",
    scrim: "#000000",
  },
  roundness: 14,
};
